<a href="https://colab.research.google.com/github/arindas/jupyter_notebooks/blob/master/pytorch_warmup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Installation:

In [2]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

tcmalloc: large alloc 1073750016 bytes == 0x57c52000 @  0x7f6a393ed2a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


## Some code snippets demonstrating Pytorch tensors:

In [3]:
dims = (3, 4)
empty_tensor = torch.empty(*dims)
print(empty_tensor)

tensor([[1.0035e-35, 0.0000e+00, 1.4013e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 3.0881e+29, 6.3828e+28],
        [3.6386e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
rand_tensor = torch.rand(*dims)
print(rand_tensor)

tensor([[0.1643, 0.5821, 0.2303, 0.2003],
        [0.8647, 0.0646, 0.4198, 0.2664],
        [0.3401, 0.4006, 0.4423, 0.7764]])


In [7]:
zero_tensor = torch.zeros(*dims)
print(zero_tensor)

unit_tensor = torch.ones(*dims)
print(unit_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [16]:
data  = [[1, 0], [0, 1]]
data_tensor = torch.tensor(data)
print(data_tensor)

new_tensor = data_tensor.new_ones(*dims, dtype=torch.double)
print(new_tensor)

rand_data_tensor = torch.randn_like(data_tensor, dtype=torch.float)
print(rand_data_tensor)

tensor([[1, 0],
        [0, 1]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8699,  0.3322],
        [ 2.9572, -0.1629]])
