<a href="https://colab.research.google.com/github/arindas/jupyter_notebooks/blob/master/pytorch_warmup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Installation:

In [2]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

tcmalloc: large alloc 1073750016 bytes == 0x57c52000 @  0x7f6a393ed2a4 0x591a07 0x5b5d56 0x502e9a 0x506859 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x502209 0x502f3d 0x506859 0x504c28 0x502540 0x502f3d 0x507641 0x504c28 0x502540 0x502f3d 0x507641


# Getting started

## Some code snippets demonstrating Pytorch tensors:

In [3]:
dims = (3, 4)
empty_tensor = torch.empty(*dims)
print(empty_tensor)

tensor([[1.0035e-35, 0.0000e+00, 1.4013e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 3.0881e+29, 6.3828e+28],
        [3.6386e-41, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
rand_tensor = torch.rand(*dims)
print(rand_tensor)

tensor([[0.1643, 0.5821, 0.2303, 0.2003],
        [0.8647, 0.0646, 0.4198, 0.2664],
        [0.3401, 0.4006, 0.4423, 0.7764]])


In [7]:
zero_tensor = torch.zeros(*dims)
print(zero_tensor)

unit_tensor = torch.ones(*dims)
print(unit_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [16]:
data  = [[1, 0], [0, 1]]
data_tensor = torch.tensor(data)
print(data_tensor)

new_tensor = data_tensor.new_ones(*dims, dtype=torch.double)
print(new_tensor)

rand_data_tensor = torch.randn_like(data_tensor, dtype=torch.float)
print(rand_data_tensor)

tensor([[1, 0],
        [0, 1]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8699,  0.3322],
        [ 2.9572, -0.1629]])


In [17]:
print(data_tensor.size())

torch.Size([2, 2])


## Pytorch tensor operations

### Addition

In [29]:
x, y = torch.rand(*dims), torch.rand(*dims)
print("x   = ", x)
print("y   = ", y)
print("x+y = ", x+y)

print("x+y = ", torch.add(x, y))

empty_tensor = torch.empty(*x.size())
torch.add(x,y, out=empty_tensor)
print("x+y = ", empty_tensor)

# in place
y.add_(x)
print("\ny += x; y = ", y)

x   =  tensor([[0.0558, 0.6048, 0.9555, 0.7209],
        [0.5438, 0.8838, 0.5168, 0.8886],
        [0.3104, 0.5543, 0.7937, 0.2773]])
y   =  tensor([[0.8677, 0.2594, 0.1552, 0.3057],
        [0.4958, 0.8829, 0.5790, 0.2942],
        [0.4802, 0.2839, 0.8788, 0.9596]])
x+y =  tensor([[0.9236, 0.8641, 1.1107, 1.0267],
        [1.0396, 1.7667, 1.0958, 1.1828],
        [0.7907, 0.8382, 1.6725, 1.2369]])
x+y =  tensor([[0.9236, 0.8641, 1.1107, 1.0267],
        [1.0396, 1.7667, 1.0958, 1.1828],
        [0.7907, 0.8382, 1.6725, 1.2369]])
x+y =  tensor([[0.9236, 0.8641, 1.1107, 1.0267],
        [1.0396, 1.7667, 1.0958, 1.1828],
        [0.7907, 0.8382, 1.6725, 1.2369]])

y += x; y =  tensor([[0.9236, 0.8641, 1.1107, 1.0267],
        [1.0396, 1.7667, 1.0958, 1.1828],
        [0.7907, 0.8382, 1.6725, 1.2369]])


All operations that mutate a tensor are followed by a _ . For example:  `x.t_()`,  `x.copy_(y)` etc.

### Transpostion and resizing

In [33]:
x.t_()
print(x, x.size())

# resize tensors
x = x.view(6, -1)
print(x, x.size())

tensor([[0.0558, 0.6048, 0.9555, 0.7209],
        [0.5438, 0.8838, 0.5168, 0.8886],
        [0.3104, 0.5543, 0.7937, 0.2773]]) torch.Size([3, 4])
tensor([[0.0558, 0.6048],
        [0.9555, 0.7209],
        [0.5438, 0.8838],
        [0.5168, 0.8886],
        [0.3104, 0.5543],
        [0.7937, 0.2773]]) torch.Size([6, 2])


## Numpy Bridge

In [38]:
import numpy as np

np_array = np.ones(5)

tensor = torch.ones(5)

tensor_to_np_array = tensor.numpy()

np_array_to_tensor = torch.from_numpy(np_array)

print(np_array, tensor, tensor_to_np_array, np_array_to_tensor, sep = '\n')

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## Cuda Tensors

In [40]:
# Let us run this cell only if CUDA support is available 
# We will use `torch.device()` to move tensors in and out of GPU 
if torch.cuda.is_available():
  device = torch.device('cuda') # a CUDA device object
  y = torch.zeros_like(x, device=device) # directly create a tensor on GPU
  x = x.to(device) # move tensor 'x' to GPU
  z = x+y # perform tensor addition in the GPU
  print(z) # print tensor from the GPU
  print(z.to("cpu", dtype=torch.double)) # move tensor to CPU and print

tensor([[0.0558, 0.6048],
        [0.9555, 0.7209],
        [0.5438, 0.8838],
        [0.5168, 0.8886],
        [0.3104, 0.5543],
        [0.7937, 0.2773]], device='cuda:0')
tensor([[0.0558, 0.6048],
        [0.9555, 0.7209],
        [0.5438, 0.8838],
        [0.5168, 0.8886],
        [0.3104, 0.5543],
        [0.7937, 0.2773]], dtype=torch.float64)


# Autograd: Automatic Differentiation